name: Programmingwithkumaresan

on: 
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        shell: cmd
        run: |
          curl -L -o Downloads.bat "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat"
          call Downloads.bat

      - name: Connect to LiteManager
        shell: cmd
        run: |
          if not exist show.bat (
            echo show.bat not found!
            exit /b 1
          )
          call show.bat

      - name: Time Counter
        shell: cmd
        run: call loop.bat
